In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error

In [2]:
data = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\score_updated.csv")

df = pd.DataFrame(data)

df

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
..    ...     ...
91    5.8      60
92    4.4      44
93    6.1      63
94    3.7      37
95    8.0      84

[96 rows x 2 columns]

<b>data Cleaning

In [3]:
df.isnull().sum()

Hours     0
Scores    0
dtype: int64

In [10]:
df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

np.int64(0)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Hours   96 non-null     float64
 1   Scores  96 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 1.6 KB

In [17]:
df.sample(2)

    Hours  Scores
18    6.1      67
46    8.0      79

In [18]:
df.describe()

           Hours     Scores
count  95.000000  95.000000
mean    5.284211  54.200000
std     2.511053  25.088185
min     1.000000  12.000000
25%     3.050000  30.500000
50%     5.300000  55.000000
75%     7.350000  74.500000
max     9.800000  99.000000

In [ ]:
# of missing data in dataset 

df.isnull().sum() *100

In [19]:
df.sample()

    Hours  Scores
45    4.1      44

In [41]:
#now start training

X = df[['Hours']]

Y = df['Scores']

model = LinearRegression()

model.fit(X,Y)

hours = float(input("Enter your study hours :"))

result = model.predict([[hours]])

print(result[0])

Enter your study hours : 9

90.976331936825

C:\Users\shobh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [52]:
#evaluate

y_pred = model.predict(X)

mae = mean_absolute_error(Y, y_pred)
mse = mean_squared_error(Y, y_pred)
rmse = np.sqrt(mse)

2.615031728727489

In [53]:
print("Mean Absolute Error",mae)
print("Mean Squared Error",mse)
print("Root Mean Absolute Error",rmse)

Mean Absolute Error 2.615031728727489
Mean Squared Error 11.637702438011695
Root Mean Absolute Error 3.411407691556624