In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\loan_approval_dataset.csv")

df = pd.DataFrame(data)

df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
# cleaning data and prepare it for machine learning

df.isnull().sum()

df.drop('loan_id', axis=1, inplace=True)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0    no_of_dependents          4269 non-null   int64
 1    education                 4269 non-null   object
 2    self_employed             4269 non-null   object
 3    income_annum              4269 non-null   int64
 4    loan_amount               4269 non-null   int64
 5    loan_term                 4269 non-null   int64
 6    cibil_score               4269 non-null   int64
 7    residential_assets_value  4269 non-null   int64
 8    commercial_assets_value   4269 non-null   int64
 9    luxury_assets_value       4269 non-null   int64
 10   bank_asset_value          4269 non-null   int64
 11   loan_status               4269 non-null   object
dtypes: int64(9), object(3)
memory usage: 400.3+ KB

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cols_to_encode = [' education', ' self_employed', ' loan_status']

for col in cols_to_encode:
    df[col] = le.fit_transform(df[col])


X = df[[' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value',]]

y = df[' loan_status']



# 0 = Approved 1 = Rejected

In [7]:
# Train Test and Split

from sklearn.model_selection import train_test_split

X_train,X_test , y_train , y_test = train_test_split(X,y , test_size = 0.2, random_state = 42)

In [8]:
# now scaling 

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
# data is ready now train classification model to genrate predictions for approved or rejected 

# logistic regression 

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()


logistic_model.fit(X_train,y_train)

prediction = logistic_model.predict(X_test)

In [10]:
#checking accuracy od model trained by : Logistic Regression 

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, prediction)

print(accuracy)

0.905152224824356

In [11]:
# now KNN 

from sklearn.neighbors import KNeighborsClassifier


knn_model = KNeighborsClassifier(n_neighbors = 3)

knn_model.fit(X_train , y_train)

knn_prediction = knn_model.predict(X_test)

In [12]:
#checking accuracy of model trained by : KNN

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, knn_prediction)

print(accuracy)

0.8934426229508197

In [13]:
# now Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier


dt_model = DecisionTreeClassifier()


dt_model.fit(X_train,y_train)

tree_prediction = dt_model.predict(X_test)

In [14]:
#checking accuracy of model trained by : Decision Tree Classifier

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, tree_prediction)

print(accuracy)

0.977751756440281

In [15]:
results = [{'Model': 'Logistic Regression', 'Accuracy': 0.905},
           {'Model': 'KNN', 'Accuracy': 0.893},
           {'Model': 'Decision Tree', 'Accuracy': 0.974}]
pd.DataFrame(results)

                 Model  Accuracy
0  Logistic Regression     0.905
1                  KNN     0.893
2        Decision Tree     0.974

In [16]:
from sklearn.metrics import classification_report

print(classification_report(y_test, tree_prediction))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       536
           1       0.97      0.97      0.97       318

    accuracy                           0.98       854
   macro avg       0.98      0.98      0.98       854
weighted avg       0.98      0.98      0.98       854

In [17]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, tree_prediction))

[[528   8]
 [ 11 307]]

In [18]:
# best accuracy and mertrics : DecisionTreeClassifier so lets save it 

import pickle

MODEL_PATH = r"C:\Users\shobh\Downloads\AI and DATA SCIENCE\𝗠𝗟 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀\Loan Approval Predictor\Model\load approval predictor.pkl"

with open(MODEL_PATH, "wb") as file:
    pickle.dump(dt_model, file)

print("Model Saved Successfully!")

Model Saved Successfully!

In [20]:
SCALER_PATH = r"C:\Users\shobh\Downloads\AI and DATA SCIENCE\𝗠𝗟 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀\Loan Approval Predictor\Model\load approval predictor scaler.pkl"

with open(SCALER_PATH, "wb") as file:
    pickle.dump(scaler, file)